config/routes.rb
Rails.application.routes.draw do

  root 'static_pages_controller#home'

  resources :gossips


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  def index

    @gossip=Gossip.all

  end
  
  def new

    @gossip = Gossip.new

  end

  def create

    @gossip= Gossip.create(gossip_params)

     redirect_to gossip_path(@gossip.id)
  end

  def show

    @gossip = Gossip.find(params[:id])
  end

  def edit

    @gossip = Gossip.find(params[:id])

  end

  def update

    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)

   

  end

  def destroy

  end

  def gossip_params
    params.require(:gossip).permit(:anonymous_author, :content)
  end


end

app/controllers/static_pages_controller_controller.rb
class StaticPagesControllerController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_controller_helper.rb
module StaticPagesControllerHelper
end

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<h1> Editer un gossip </h1>


<%= form_for @gossip do |f|%>

<div class="from-group">

<label> Titre du gossip </label>

<%= f.text_field :content %>


<label> Nom de l'auteur </label>

<%= f.text_field :anonymous_author %>

<%= f.submit "Editer"%>

</div>

<% end %>

<p>
<a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-confirm="Etes-vous sûr de supprimer ce potin ?" data-method="delete">Supprimer le Gossip</a>
</p>

app/views/gossips/index.html.erb
<h1>Liste des Gossips</h1>

<table>

  <thead>
    <th>Gossip</th>
    <th>Lien vers la page</th>
    <th>Nb de commentaires</th>
  </thead>

  <tbody>

    <% @gossip.each do |gossip| %>
    <tr>
      <td> <%= gossip.content %> </td>
      <td> <a href="<%= gossip_path(gossip.id) %>">Voir la page du Gossip</a></td>
      r
    <% end %>

  </tbody>

</table>

app/views/gossips/new.html.erb
<h1> Créer un nouveau gossip </h1>


<%= form_for @gossip do |f|%>

<div class="from-group">

<label> Titre du gossip </label>

<%= f.text_field :content %>


<label> Nom de l'auteur </label>

<%= f.text_field :anonymous_author %>

<%= f.submit "Créer"%>

</div>

<% end %>

app/views/gossips/show.html.erb
<h1> Détail du gossip </h1>
<p> <%= @gossip.content %> </p>


<p>

<a href="<%=gossips_path%>"  class="btn btn-primary">Revenir aux gossips </a>

<a href="<%=edit_gossip_path%>" class="btn btn-primary">Editer le gossip </a>
 

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", '/' %></li>
        <li><%= link_to "Index des gossips", gossips_path%></li>
        <li><%= link_to "Nouveau gossip", new_gossip_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  
  </head>

  <body>
  <%=render"layouts/header"%>
    <%= yield %>

  </body>
</html>

app/views/static_pages_controller/home.html.erb
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", '#', class: "btn btn-lg btn-primary" %>
</div>